# Generated by Django 4.2.5 on 2023-09-22 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Image", models.ImageField(upload_to="images")),
                ("Title", models.CharField(default="Image", max_length=50)),
                ("Description", models.CharField(max_length=100, null=True)),
                (
                    "Owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("EventTitle", models.CharField(max_length=12)),
                ("EventDate", models.DateField()),
                ("EventTimeStart", models.TimeField()),
                ("EventTimeEnd", models.TimeField()),
                ("EventLocation", models.CharField(max_length=50)),
                ("EventDescription", models.CharField(max_length=100)),
                ("EventIsPrivate", models.BooleanField(default=False)),
                ("EventIsCancelled", models.BooleanField(default=False)),
                ("EventIsFree", models.BooleanField(default=False)),
                ("EventPrice", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ("EventMaxGuests", models.IntegerField(default=50)),
                ("EventCurrentGuests", models.IntegerField(default=0)),
                ("EventMinimumAge", models.IntegerField(default=0)),
                ("EventOrganizer", models.CharField(max_length=50)),
                (
                    "EventInvitedGuests",
                    models.ManyToManyField(blank=True, related_name="event_guests", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "EventOwner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
