# Generated by Django 4.2.5 on 2023-09-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_event_eventbanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="EventBanner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_banners",
                to="api.image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="EventInvitedGuests",
            field=models.ManyToManyField(related_name="invited_to_events", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="image",
            name="Owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
