# Generated by Django 4.1.3 on 2022-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=32)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('age', models.IntegerField(verbose_name='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
