# Generated by Django 4.1.3 on 2023-09-28 16:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="QrUid",
            field=models.CharField(default=uuid.uuid4, max_length=8, unique=True),
        ),
    ]
