# Generated by Django 4.1.3 on 2022-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
