# Generated by Django 4.1.3 on 2023-09-29 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_qruid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
