# Generated by Django 4.1.3 on 2022-11-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qrcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
