# Generated by Django 4.1.3 on 2022-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_options_users_emailadress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=1),
        ),
    ]
