# Generated by Django 4.1.3 on 2023-09-29 08:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="QrUid",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
