# Generated by Django 4.1.3 on 2022-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_qruid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='QrUid',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
