# Generated by Django 4.1.3 on 2022-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='emailadress',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
