# Generated by Django 4.1.3 on 2022-11-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_passwords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
