# Generated by Django 4.1.3 on 2023-10-04 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_event_eventinvitedguests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="EventInvitedGuests",
            field=models.ManyToManyField(blank=True, related_name="invited_to_events", to=settings.AUTH_USER_MODEL),
        ),
    ]
