# Generated by Django 4.1.3 on 2022-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_users_id_users_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
