# Generated by Django 4.1.3 on 2022-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
