# Generated by Django 4.1.3 on 2023-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default="1970-01-01"),
        ),
    ]
