# Generated by Django 4.1.3 on 2023-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="EventBanner",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
