# Generated by Django 4.1.3 on 2022-12-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_age_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventTitle', models.CharField(max_length=50)),
                ('EventDate', models.DateField()),
                ('EventTimeStart', models.TimeField()),
                ('EventTimeEnd', models.TimeField()),
                ('EventLocation', models.CharField(max_length=50)),
                ('EventDescription', models.CharField(max_length=100)),
                ('EventIsPrivate', models.BooleanField(default=False)),
                ('EventIsCancelled', models.BooleanField(default=False)),
                ('EventIsFree', models.BooleanField(default=False)),
                ('EventPrice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('EventDuration', models.TimeField()),
                ('EventMaxGuests', models.IntegerField()),
                ('EventCurrentGuests', models.IntegerField()),
                ('EventMinimumAge', models.IntegerField()),
                ('EventOrganizer', models.CharField(max_length=50)),
                ('EventInvitedGuests', models.ManyToManyField(related_name='EventGuests', to=settings.AUTH_USER_MODEL)),
                ('EventOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
