# Generated by Django 4.1.3 on 2022-12-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventCurrentGuests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventMaxGuests',
            field=models.IntegerField(default=50),
        ),
    ]
