# Generated by Django 4.1.3 on 2022-12-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_event_eventcurrentguests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDuration',
            field=models.DurationField(),
        ),
    ]
