# Generated by Django 4.1.3 on 2022-12-21 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_event_eventduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventOrganizer',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=50),
        ),
    ]
