# Generated by Django 4.1.3 on 2022-12-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_event_eventorganizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventMinimumAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventOrganizer',
            field=models.CharField(max_length=50),
        ),
    ]
