# Generated by Django 4.1.3 on 2022-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_eventduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDuration',
            field=models.DurationField(),
        ),
    ]
