# Generated by Django 4.1.3 on 2022-12-21 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_event_eventduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventInvitedGuests',
            field=models.ManyToManyField(blank=True, related_name='EventGuests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
