# Generated by Django 4.1.3 on 2022-12-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_event_eventinvitedguests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventDuration',
        ),
    ]
