# Generated by Django 4.1.3 on 2022-12-22 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_event_eventduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
