# Generated by Django 4.1.3 on 2023-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_image_imagedescription_image_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ImageDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='ImageOwner',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='ImageName',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
