# Generated by Django 4.1.3 on 2023-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_imagedescription_image_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
