# Generated by Django 4.1.3 on 2023-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_image_linkedtoevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventIsCancelled',
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTitle',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
