# Generated by Django 4.1.3 on 2023-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_event_eventiscancelled_alter_event_eventtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventIsCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
