# Generated by Django 4.1.3 on 2023-01-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventBanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventBanner', to='api.image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Images',
            field=models.ManyToManyField(blank=True, related_name='UserImages', to='api.image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ProfilePicture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProfilePicture', to='api.image'),
        ),
    ]
