#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/gatekeeper_backend/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn gatekeeper_backend.wsgi --bind 0.0.0.0:5000 --chdir=/app
